export const sampleProductList = [
  {
    _id: "1",
    image:
      "https://aidaptive.com/wp-content/uploads/2023/04/blog-personalization-dtc-ecommerce.jpg",
    title: "Personalized E-Commerce Experience",
    description:
      "Enhance customer engagement with personalized shopping experiences that drive sales.",
    category: "Accessories",
    brand: "Zara",
    price: 299.99,
    salePrice: 249.99,
    totalStock: 50,
  },
  {
    _id: "2",
    image:
      "https://dl-cf.splento.com/cdn/2020/05/27/jeans_sweater_1200_630.jpg",
    title: "Casual Jeans and Sweater Set",
    description:
      "Stylish and comfortable jeans paired with a cozy sweater, perfect for any casual occasion.",
    category: "Men",
    brand: "Levi's",
    price: 79.99,
    salePrice: 59.99,
    totalStock: 100,
  },
  {
    _id: "3",
    image:
      "https://assets.indiabizforsale.com/business/upload_pic/skirts_218d01db114b1ad852eb29ac9444e5f1_6925ff769547e27ae23369041409de84.jpg",
    title: "Elegant Skirt",
    description:
      "A beautiful skirt that combines elegance and comfort, suitable for both casual and formal events.",
    category: "Women",
    brand: "Zara",
    price: 49.99,
    salePrice: 39.99,
    totalStock: 75,
  },
  {
    _id: "4",
    image:
      "https://www.pymnts.com/wp-content/uploads/2021/01/ecommerce-clothing.jpg?w=620",
    title: "E-Commerce Clothing Collection",
    description:
      "A curated collection of trendy clothing designed for online shopping, enhancing your wardrobe effortlessly.",
    category: "Women",
    brand: "H&M",
    price: 199.99,
    salePrice: 159.99,
    totalStock: 40,
  },
  {
    _id: "5",
    image:
      "https://images-eu.ssl-images-amazon.com/images/I/61uA2UVnYWL._AC_UL165_SR165,165_.jpg",
    title: "Dell XPS 13",
    description:
      "A high-performance laptop with a stunning 13-inch InfinityEdge display.",
    category: "Accessories",
    brand: "Nike",
    price: 999.99,
    salePrice: 899.99,
    totalStock: 30,
  },
  {
    _id: "6",
    image:
      "https://images-eu.ssl-images-amazon.com/images/I/71ez69tPl4L._AC_UL165_SR165,165_.jpg",
    title: "Apple MacBook Air",
    description:
      "Lightweight and powerful laptop with M1 chip and Retina display.",
    category: "Accessories",
    brand: "Adidas",
    price: 999.0,
    salePrice: 899.0,
    totalStock: 50,
  },
  {
    _id: "7",
    image: "https://m.media-amazon.com/images/I/51d6wWFtkcL._SY741_.jpg",
    title: "Instant Pot Duo 7-in-1",
    description:
      "Multifunctional pressure cooker that makes cooking quick and easy.",
    category: "Accessories",
    brand: "Nike",
    price: 89.99,
    salePrice: 79.99,
    totalStock: 200,
  },
  {
    _id: "8",
    image: "https://m.media-amazon.com/images/I/71HBNT3R66L._SX679_.jpg",
    title: "Fitbit Charge 5",
    description: "Advanced fitness and health tracker with built-in GPS.",
    category: "Accessories",
    brand: "Adidas",
    price: 179.95,
    salePrice: 149.95,
    totalStock: 150,
  },
  {
    _id: "9",
    image: "https://m.media-amazon.com/images/I/61kZXsFe7CL._SX679_.jpg",
    title: "GoPro HERO10 Black",
    description:
      "Versatile action camera with 5.3K video and advanced stabilization.",
    category: "Footwear",
    brand: "Puma",
    price: 499.99,
    salePrice: 399.99,
    totalStock: 80,
  },
  {
    _id: "10",
    image: "https://m.media-amazon.com/images/I/51NxYf0jVPL._SX679_.jpg",
    title: "Samsung 55-Inch QLED TV",
    description: "Stunning 4K QLED TV with vibrant colors and smart features.",
    category: "Accessories",
    brand: "Zara",
    price: 899.99,
    salePrice: 749.99,
    totalStock: 20,
  },
  {
    _id: "11",
    image: "https://m.media-amazon.com/images/I/71Mf7Es+qiL._SY879_.jpg",
    title: "Apple AirPods Pro",
    description:
      "Wireless earphones with active noise cancellation and transparency mode.",
    category: "Accessories",
    brand: "Nike",
    price: 249.0,
    salePrice: 199.0,
    totalStock: 100,
  },
  {
    _id: "12",
    image:
      "https://m.media-amazon.com/images/I/41eyofYVPpL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy Watch 5",
    description:
      "Advanced health and fitness tracker with body composition analysis.",
    category: "Accessories",
    brand: "Adidas",
    price: 299.99,
    salePrice: 249.99,
    totalStock: 120,
  },
  {
    _id: "13",
    image:
      "https://m.media-amazon.com/images/I/81xCdA+1u9L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Nikon D5600 DSLR Camera",
    description:
      "A versatile DSLR camera with 24.2 MP sensor and full HD video recording.",
    category: "Accessories",
    brand: "Puma",
    price: 699.99,
    salePrice: 599.99,
    totalStock: 40,
  },
  {
    _id: "14",
    image: "https://m.media-amazon.com/images/I/51wNzje3v3L._SY741_.jpg",
    title: "LG OLED C1 Series 55-Inch TV",
    description:
      "A stunning OLED display with Dolby Vision and AI-powered 4K upscaling.",
    category: "Accessories",
    brand: "H&M",
    price: 1299.99,
    salePrice: 1099.99,
    totalStock: 30,
  },
  {
    _id: "15",
    image:
      "https://m.media-amazon.com/images/I/811NamPj4IL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Sony PlayStation 5",
    description:
      "Next-gen gaming console with ultra-high speed SSD and ray tracing.",
    category: "Footwear",
    brand: "Nike",
    price: 499.99,
    salePrice: 449.99,
    totalStock: 200,
  },
  {
    _id: "16",
    image:
      "https://rukminim2.flixcart.com/image/150/150/kc0u7bk0/watch/c/r/u/mt-gr904-ylbk-metronaut-original-imaft84wvt2jfegz.jpeg?q=70",
    title: "Amazon Echo Show 8",
    description:
      "Smart display with Alexa for video calls, streaming, and more.",
    category: "Accessories",
    brand: "Puma",
    price: 129.99,
    salePrice: 99.99,
    totalStock: 250,
  },
  {
    _id: "17",
    image:
      "https://rukminim2.flixcart.com/image/150/150/xif0q/shoe/j/5/5/7-gb9974-8-reebok-blue-original-imagztc6kzg9xneq.jpeg?q=70",
    title: "Logitech MX Master 3",
    description:
      "Advanced wireless mouse with hyper-fast scrolling and ergonomic design.",
    category: "Accessories",
    brand: "Levi's",
    price: 99.99,
    salePrice: 79.99,
    totalStock: 150,
  },
  {
    _id: "18",
    image:
      "https://rukminim2.flixcart.com/image/150/150/xif0q/shoe/j/5/5/7-gb9974-8-reebok-blue-original-imagztc6kzg9xneq.jpeg?q=70",
    title: "Reebok Running Shoes",
    description:
      "Comfortable running shoes with lightweight design and superior cushioning.",
    category: "Footwear",
    brand: "Reebok",
    price: 69.99,
    salePrice: 49.99,
    totalStock: 100,
  },
  {
    _id: "19",
    image:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/trouser/z/f/v/-original-imah4m7gzrbyfzqw.jpeg?q=70",
    title: "Dell Inspiron 15",
    description: "15-inch laptop with Intel Core i5 and full HD display.",
    category: "Laptops",
    brand: "Dell",
    price: 649.99,
    salePrice: 599.99,
    totalStock: 80,
  },
  {
    _id: "20",
    image: "https://m.media-amazon.com/images/I/81sZ1E9VUKL._AC_SX569_.jpg",
    title: "HP Pavilion Gaming Laptop",
    description:
      "Affordable gaming laptop with AMD Ryzen 5 and NVIDIA GTX 1650.",
    category: "Laptops",
    brand: "HP",
    price: 749.99,
    salePrice: 649.99,
    totalStock: 60,
  },
  {
    _id: "21",
    image: "https://m.media-amazon.com/images/I/7112J4WQGiL._AC_SX679_.jpg",
    title: "Razer Blade 15",
    description:
      "High-end gaming laptop with a sleek design and powerful performance.",
    category: "Laptops",
    brand: "Razer",
    price: 1999.99,
    salePrice: 1799.99,
    totalStock: 40,
  },
  {
    _id: "22",
    image: "https://m.media-amazon.com/images/I/81XDLpZT+2L._AC_SX569_.jpg",
    title: "Samsung Galaxy Tab S7",
    description: "Powerful tablet with 11-inch display and S Pen included.",
    category: "Tablets",
    brand: "Samsung",
    price: 649.99,
    salePrice: 599.99,
    totalStock: 75,
  },
  {
    _id: "23",
    image: "https://m.media-amazon.com/images/I/71Vyr9XjRGL._AC_SX679_.jpg",
    title: "Microsoft Surface Pro 8",
    description: "2-in-1 tablet with a stunning 13-inch PixelSense display.",
    category: "Tablets",
    brand: "Microsoft",
    price: 999.99,
    salePrice: 899.99,
    totalStock: 30,
  },
  {
    _id: "24",
    image: "https://m.media-amazon.com/images/I/51dsSz67jtL._AC_SX679_.jpg",
    title: "Lenovo Yoga 9i",
    description:
      "Versatile laptop with a 14-inch touchscreen and powerful performance.",
    category: "Laptops",
    brand: "Lenovo",
    price: 1399.99,
    salePrice: 1299.99,
    totalStock: 50,
  },
  {
    _id: "25",
    image:
      "https://m.media-amazon.com/images/I/71vk1UJniHL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    title: "Logitech G502 HERO",
    description:
      "High-performance gaming mouse with customizable RGB lighting.",
    category: "Computer Accessories",
    brand: "Logitech",
    price: 49.99,
    salePrice: 39.99,
    totalStock: 100,
  },
  {
    _id: "26",
    image:
      "https://m.media-amazon.com/images/I/41m5Vryt83L.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    title: "Fitbit Versa 3",
    description:
      "Health and fitness smartwatch with built-in GPS and voice assistant.",
    category: "Wearables",
    brand: "Fitbit",
    price: 229.95,
    salePrice: 199.95,
    totalStock: 150,
  },
  {
    _id: "27",
    image:
      "https://m.media-amazon.com/images/I/81d4PSIol4L._AC_UL480_FMwebp_QL65_.jpg",
    title: "GoPro HERO9 Black",
    description: "Action camera with 5K video and hyper smooth stabilization.",
    category: "Cameras",
    brand: "GoPro",
    price: 399.99,
    salePrice: 349.99,
    totalStock: 80,
  },
  {
    _id: "28",
    image:
      "https://m.media-amazon.com/images/I/61nQuejTUGL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Nikon Z50",
    description:
      "Compact mirrorless camera with a 20.9 MP sensor and 4K video recording.",
    category: "Cameras",
    brand: "Nikon",
    price: 999.99,
    salePrice: 899.99,
    totalStock: 25,
  },
  {
    _id: "29",
    image: "https://m.media-amazon.com/images/I/81HHSNG-nhL._AC_SX679_.jpg",
    title: "Samsung Galaxy Buds Live",
    description:
      "True wireless earbuds with active noise cancellation and long battery life.",
    category: "Audio",
    brand: "Samsung",
    price: 169.99,
    salePrice: 149.99,
    totalStock: 200,
  },
  {
    _id: "30",
    image: "https://m.media-amazon.com/images/I/71zP3e9ev7L._AC_SY741_.jpg",
    title: "Anker Soundcore Life Q30",
    description:
      "Active noise cancelling headphones with superior sound quality.",
    category: "Audio",
    brand: "Anker",
    price: 129.99,
    salePrice: 99.99,
    totalStock: 120,
  },
];
